### ISSUE TITLE
Error fething notion API

### ISSUE THREAD

**Issue by Dillie-O** [dinhanhthi/dinhanhthi.com#28]
Greetings! 

I found your 11ty "theme" and am really hoping to tweak it a little to use it as my own personal site. It's very impressive. I'm walking through the basic steps, had to add a dependency for eleventy-fetch and now I'm getting some error about not being able to access a notion API. Any chance this is a configuration or something I'm missing? Here's a snapshot from my output. Thanks in advance!

```
[js] rollup v2.79.1
[js] bundles src/js/main.js → src/js/main.min.js...
[js] created src/js/main.min.js in 131ms
[css]
[css] > dinhanhthi.com@4.12.1 css:build
[css] > node-sass src/css/main.scss src/css/main.css
[css]
[css] Rendering Complete, saving .css file...
[css] Wrote CSS to /home/dillieo/projects/dinhanhthi.com/src/css/main.css
[11ty] [11ty] Bad response for https://api.notion.com/v1/databases/undefined/query (401): Unauthorized (via Error)
[11ty] [11ty]
[11ty] [11ty] Original error stack trace: Error: Bad response for https://api.notion.com/v1/databases/undefined/query (401): Unauthorized
[11ty] [11ty]     at RemoteAssetCache.fetch (/home/dillieo/projects/dinhanhthi.com/node_modules/@11ty/eleventy-fetch/src/RemoteAssetCache.js:73:11)
[11ty] [11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11ty] [11ty]     at async run (/home/dillieo/projects/dinhanhthi.com/node_modules/p-queue/dist/index.js:163:29)
[11ty] npm run full:serve-no-opt exited with code 1
```

**Comment by Dillie-O** [comment]
Well, the quick solution is to simply remove the notion.json file to prevent it from handling some of the links. That's not really the "correct" answer I suppose, but at least it gets around the issue or maybe there is a way in the future to had a flag to disable handling of notion links in that manner. Thank you regardless!

**Comment by dinhanhthi** [comment]
Hello, thank you for using my theme :) The error you encountered is related to the display of notion notes on the site. If you have notion notes and you want to display their title and URL on your 11ty website, you can use notion.js (of course you need to do some more settings to use notion API). If you do not use notion api, just follow [this hint](https://dinhanhthi.com/notion-11ty/) (but in the opposite direction).
