### ISSUE TITLE
error deploy during run this site in github

### ISSUE THREAD

**Issue by mohammadRezaeian** [dinhanhthi/dinhanhthi.com#35]
```
  with:
    source: .
    destination: ./_site
    future: false
    build_revision: 9e91f682814d4f64b47a7169343a85d5591bf36e
    verbose: true
    token: ***
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv108_98e7ce --label c9a4a5 --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/mohammadrezaeian.github.io/mohammadrezaeian.github.io":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.8
Configuration file: none
  Logging at level: debug
      GitHub Pages: github-pages v228
      GitHub Pages: jekyll v3.9.3
             Theme: jekyll-theme-primer
      Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0
         Requiring: jekyll-github-metadata
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
     Build Warning: Layout 'blog' requested in sample_posts/2022-06-12-sample-blog-post.md does not exist.
  Liquid Exception: Liquid syntax error (line 10): Unknown tag 'set' in pages/about.njk
/usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block.rb:38:in `unknown_tag': Liquid syntax error (line 10): Unknown tag 'set' (Liquid::SyntaxError)
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/for.rb:69:in `unknown_tag'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block.rb:68:in `block in parse_body'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:32:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block.rb:58:in `parse_body'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/for.rb:60:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tag.rb:10:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:34:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block.rb:58:in `parse_body'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/for.rb:60:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tag.rb:10:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:34:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/document.rb:10:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/document.rb:5:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:130:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:114:in `parse'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:121:in `render_liquid'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:79:in `render_document'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:62:in `run'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:479:in `render_regenerated'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:472:in `block in render_pages'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:471:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:471:in `render_pages'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:192:in `render'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:71:in `process'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
         Requiring: jekyll-seo-tag
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-gist
         Requiring: jekyll-github-metadata
         Requiring: jekyll-paginate
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
   GitHub Metadata: Initializing...
            Source: /github/workspace/.
       Destination: /github/workspace/./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
        Generating: JekyllOptionalFrontMatter::Generator finished in 0.000310304 seconds.
        Generating: JekyllReadmeIndex::Generator finished in 0.002463135 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 4.3e-06 seconds.
        Generating: JekyllRelativeLinks::Generator finished in 0.001217018 seconds.
        Generating: JekyllDefaultLayout::Generator finished in 0.000215403 seconds.
         Requiring: kramdown-parser-gfm
        Generating: JekyllTitlesFromHeadings::Generator finished in 0.009160633 seconds.
         Rendering: sample_posts/2021-10-05-sample-all-tags.md
  Pre-Render Hooks: sample_posts/2021-10-05-sample-all-tags.md
  Rendering Markup: sample_posts/2021-10-05-sample-all-tags.md
  Rendering Layout: sample_posts/2021-10-05-sample-all-tags.md
     Layout source: theme
   GitHub Metadata: Generating for mohammadRezaeian/mohammadrezaeian.github.io
   GitHub Metadata: Calling @client.repository("mohammadRezaeian/mohammadrezaeian.github.io", {:accept=>"application/vnd.github.drax-preview+json"})
   GitHub Metadata: Calling @client.pages("mohammadRezaeian/mohammadrezaeian.github.io", {})
         Rendering: sample_posts/2022-06-12-sample-blog-post.md
  Pre-Render Hooks: sample_posts/2022-06-12-sample-blog-post.md
  Rendering Liquid: sample_posts/2022-06-12-sample-blog-post.md
  Rendering Markup: sample_posts/2022-06-12-sample-blog-post.md
  Rendering Layout: sample_posts/2022-06-12-sample-blog-post.md
         Rendering: pages/404.md
  Pre-Render Hooks: pages/404.md
  Rendering Markup: pages/404.md
  Rendering Layout: pages/404.md
     Layout source: theme
         Rendering: pages/about-the-notes.md
  Pre-Render Hooks: pages/about-the-notes.md
  Rendering Markup: pages/about-the-notes.md
  Rendering Layout: pages/about-the-notes.md
     Layout source: theme
         Rendering: pages/about.njk
  Pre-Render Hooks: pages/about.njk
  Rendering Liquid: pages/about.njk
github-pages 228 | Error:  Liquid syntax error (line 10): Unknown tag 'set'
```

**Comment by dinhanhthi** [comment]
Hi everyone I do not know which version you are using. I see you are using Jekyll, whereas the current version in this repository only supports 11ty. I am afraid I can not help you any further, sorry.

If you are using the older versions, please go to the appropriate repositories. Note that the Github Pages aren't so good for the custom themes. I recommend you use Netlify or Vercel instead.

**Comment by mohammadRezaeian** [comment]
I use your last commit on final version
Version 1 to 3 before write new configuration ( I mean creating files with .njk format )  they are work fin and can deploying
And 
I want use github for host website 
And github just has github page
And I just trying use it
